"use client"

import { useState } from "react"
import Image from "next/image"
import { useQuery } from "@tanstack/react-query"
import { BringToFront, ChevronDown, ChevronUp, Link as LinkIcon, MoveDiagonal2, SendToBack } from "lucide-react"
import { Popover, PopoverAnchor, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import {
  BG_SWATCHES,
  BLOCK_LIBRARY,
  CANVAS_WIDTH,
  CHOICE_FIELD_TYPES,
  MIN_BLOCK_HEIGHT,
  MIN_BLOCK_WIDTH,
  TEXT_SWATCHES,
  clampX,
  newBlock,
  newImageBlock,
  nextFreeY,
  type Block,
  type BlockType,
} from "./blocks"

type ReorderAction = "front" | "back" | "forward" | "backward"

// Reads a manifest generated by scripts/build-assets.mjs rather than asking a
// route handler to list public/ at request time. Directory listing needs a
// filesystem, which a serverless/edge runtime does not have — and the filenames
// cannot change between deploys anyway, so computing this per request was only
// ever doing build-time work at runtime.
function useLocalImages() {
  return useQuery({
    queryKey: ["local-images"],
    staleTime: Infinity,
    queryFn: async () => {
      const res = await fetch("/image-manifest.json")
      if (!res.ok) return []
      const json = (await res.json()) as { images: string[] }
      return json.images
    },
  })
}

export function CanvasBuilder() {
  const [blocks, setBlocks] = useState<Block[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [canvasBg, setCanvasBg] = useState<string>("#ffffff")
  const imagesQuery = useLocalImages()
  const images = imagesQuery.data ?? []

  function appendBlock(type: Exclude<BlockType, "image">) {
    const y = blocks.length === 0 ? 24 : nextFreeY(blocks) + 20
    const b = newBlock(type, 40, y)
    setBlocks((prev) => [...prev, b])
    setSelectedId(b.id)
  }

  function appendImage(src: string) {
    const y = blocks.length === 0 ? 24 : nextFreeY(blocks) + 20
    const b = newImageBlock(src, 40, y)
    setBlocks((prev) => [...prev, b])
    setSelectedId(b.id)
  }

  function updateBlock(id: string, patch: Partial<Block>) {
    setBlocks((prev) => prev.map((b) => (b.id === id ? { ...b, ...patch } : b)))
  }

  function deleteBlock(id: string) {
    setBlocks((prev) => prev.filter((b) => b.id !== id))
    setSelectedId((s) => (s === id ? null : s))
  }

  // Stacking order among top-level blocks is just array order (later =
  // painted on top) — reordering the array is all "bring to front" etc need.
  function reorderBlock(id: string, action: ReorderAction) {
    setBlocks((prev) => {
      const idx = prev.findIndex((b) => b.id === id)
      if (idx === -1) return prev
      const arr = [...prev]
      const [item] = arr.splice(idx, 1)
      if (action === "front") arr.push(item)
      else if (action === "back") arr.unshift(item)
      else if (action === "forward") arr.splice(Math.min(idx + 1, arr.length), 0, item)
      else arr.splice(Math.max(idx - 1, 0), 0, item)
      return arr
    })
  }

  const canvasHeight = Math.max(600, nextFreeY(blocks) + 200)

  return (
    <div className="grid gap-5 lg:grid-cols-[240px_1fr]" onClick={() => setSelectedId(null)}>
      <div className="space-y-5" onClick={(e) => e.stopPropagation()}>
        <div className="space-y-2">
          <p className="px-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Blocks</p>
          {BLOCK_LIBRARY.filter((b) => b.group === "content").map((b) => (
            <button
              key={b.type}
              onClick={() => appendBlock(b.type)}
              className="flex w-full cursor-pointer items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-left text-sm font-semibold text-brand-900 transition-colors hover:border-(--royal-blue)/30 hover:bg-(--royal-blue)/5"
            >
              + {b.label}
            </button>
          ))}
        </div>

        <div className="space-y-2">
          <p className="px-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Form fields</p>
          {BLOCK_LIBRARY.filter((b) => b.group === "field").map((b) => (
            <button
              key={b.type}
              onClick={() => appendBlock(b.type)}
              className="flex w-full cursor-pointer items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-left text-sm font-semibold text-brand-900 transition-colors hover:border-(--royal-blue)/30 hover:bg-(--royal-blue)/5"
            >
              + {b.label}
            </button>
          ))}
        </div>

        <div className="space-y-2">
          <p className="px-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Images</p>
          {imagesQuery.isLoading ? (
            <p className="px-1 text-xs text-slate-400">Loading…</p>
          ) : images.length === 0 ? (
            <p className="px-1 text-xs text-slate-400">No images found in /public.</p>
          ) : (
            <ImagePickerGrid images={images} onPick={appendImage} />
          )}
        </div>

        <p className="px-1 text-xs text-slate-400">
          Press and drag a block to move it, drag its bottom-right corner to resize. Click a block for colors and
          layer order.
        </p>
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-3 py-2">
          <span className="text-xs font-semibold uppercase tracking-wide text-slate-400">Board color</span>
          <div className="flex items-center gap-1.5">
            {["#ffffff", "#f5efe4", "#0c1D37", "#f8fafc"].map((c) => (
              <button
                key={c}
                onClick={() => setCanvasBg(c)}
                style={{ background: c }}
                className={`h-5 w-5 rounded-full border-2 ${canvasBg === c ? "border-(--royal-blue)" : "border-slate-200"}`}
              />
            ))}
            <input
              type="color"
              value={canvasBg}
              onChange={(e) => setCanvasBg(e.target.value)}
              className="h-5 w-5 cursor-pointer rounded-full border-2 border-slate-200 p-0"
            />
          </div>
        </div>

        {/* Fixed-width canvas — scrolls horizontally if the viewport is
            narrower, same model as a real design-tool canvas. Positions are
            plain pixels within this fixed frame, so they never depend on a
            measured/responsive container width. */}
        <div className="overflow-x-auto rounded-2xl border border-dashed border-slate-300">
          <div
            className="relative"
            style={{
              width: CANVAS_WIDTH,
              height: canvasHeight,
              backgroundColor: canvasBg,
              backgroundImage:
                "linear-gradient(to right, rgba(15,23,42,0.06) 1px, transparent 1px), linear-gradient(to bottom, rgba(15,23,42,0.06) 1px, transparent 1px)",
              backgroundSize: "24px 24px",
            }}
          >
            {blocks.length === 0 && (
              <p className="pointer-events-none absolute inset-0 grid place-items-center text-sm text-slate-400">
                Add a block to get started.
              </p>
            )}
            {blocks.map((b, i) => (
              <CanvasBlock
                key={b.id}
                block={b}
                stackIndex={i}
                images={images}
                selected={selectedId === b.id}
                onSelect={() => setSelectedId(b.id)}
                onDeselect={() => setSelectedId(null)}
                onChange={(patch) => updateBlock(b.id, patch)}
                onDelete={() => deleteBlock(b.id)}
                onReorder={(action) => reorderBlock(b.id, action)}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

function ImagePickerGrid({ images, onPick }: { images: string[]; onPick: (src: string) => void }) {
  return (
    <div className="grid grid-cols-3 gap-1.5">
      {images.map((src) => (
        <button
          key={src}
          onClick={() => onPick(src)}
          className="relative aspect-square overflow-hidden rounded-lg ring-1 ring-slate-200 transition hover:ring-2 hover:ring-(--royal-blue)"
          title={src}
        >
          <Image src={src} alt="" fill draggable={false} sizes="80px" className="object-cover" />
        </button>
      ))}
    </div>
  )
}

function textClassFor(type: BlockType): string {
  if (type === "heading") return "font-bricolage text-2xl font-bold leading-tight outline-none"
  if (type === "subheading") return "font-bricolage text-lg font-semibold leading-tight outline-none"
  if (type === "quote") return "border-l-4 border-(--gold) pl-3 text-sm italic leading-relaxed text-slate-700 outline-none"
  if (type === "button")
    return "grid h-full w-full place-items-center rounded-lg text-center text-sm font-semibold outline-none"
  if (type === "badge")
    return "grid h-full w-full place-items-center rounded-full px-2 text-center text-xs font-semibold outline-none"
  return "text-sm leading-relaxed outline-none"
}

const FIELD_LABEL_CLS = "text-sm font-medium text-brand-900 outline-none"
const FIELD_BOX_CLS = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-400"

/** The recruitment form's field types (lib/recruitment.ts), as static
 * preview blocks — visual only, no real input state, this canvas has no
 * backend. */
function FormFieldContent({ block, onChange }: { block: Block; onChange: (patch: Partial<Block>) => void }) {
  const label = (
    <div
      contentEditable
      suppressContentEditableWarning
      onBlur={(e) => onChange({ text: e.currentTarget.textContent ?? "" })}
      className={FIELD_LABEL_CLS}
    >
      {block.text}
    </div>
  )

  if (block.type === "field_short_text") {
    return (
      <div className="flex h-full w-full flex-col gap-1.5">
        {label}
        <div className={FIELD_BOX_CLS}>Your answer</div>
      </div>
    )
  }
  if (block.type === "field_paragraph") {
    return (
      <div className="flex h-full w-full flex-col gap-1.5">
        {label}
        <div className={`${FIELD_BOX_CLS} flex-1`}>Your answer</div>
      </div>
    )
  }
  if (block.type === "field_dropdown") {
    return (
      <div className="flex h-full w-full flex-col gap-1.5">
        {label}
        <div className={`${FIELD_BOX_CLS} flex items-center justify-between`}>
          <span>{block.options[0] ?? "Select…"}</span>
          <span>⌄</span>
        </div>
      </div>
    )
  }
  if (block.type === "field_single_choice" || block.type === "field_multi_choice") {
    const round = block.type === "field_single_choice"
    return (
      <div className="flex h-full w-full flex-col gap-1.5 overflow-auto">
        {label}
        <div className="space-y-1.5">
          {block.options.map((o, i) => (
            <div key={i} className="flex items-center gap-2 text-sm text-slate-600">
              <span className={`h-3.5 w-3.5 shrink-0 border border-slate-300 ${round ? "rounded-full" : "rounded"}`} />
              {o}
            </div>
          ))}
        </div>
      </div>
    )
  }
  // field_link
  return (
    <div className="flex h-full w-full items-center gap-2 rounded-lg border border-(--gold-soft-border) bg-(--gold-soft-bg) px-3 text-sm font-semibold text-brand-900">
      <LinkIcon size={14} className="shrink-0 text-(--gold-icon)" />
      <div
        contentEditable
        suppressContentEditableWarning
        onBlur={(e) => onChange({ text: e.currentTarget.textContent ?? "" })}
        className="flex-1 truncate outline-none"
      >
        {block.text}
      </div>
    </div>
  )
}

function BlockContent({ block, onChange }: { block: Block; onChange: (patch: Partial<Block>) => void }) {
  if (block.type === "divider") {
    return (
      <div className="flex h-full w-full items-center">
        <div className="h-0.5 w-full rounded-full" style={{ background: block.bg ?? "#cbd5e1" }} />
      </div>
    )
  }
  if (block.type === "image") {
    return block.src ? (
      <Image src={block.src} alt="" fill draggable={false} sizes={`${block.width}px`} className="rounded-lg object-contain" />
    ) : null
  }
  if (block.type.startsWith("field_")) {
    return <FormFieldContent block={block} onChange={onChange} />
  }
  return (
    <div
      contentEditable
      suppressContentEditableWarning
      onBlur={(e) => onChange({ text: e.currentTarget.textContent ?? "" })}
      className={textClassFor(block.type)}
    >
      {block.text}
    </div>
  )
}

const HOLD_DELAY_MS = 200
const HOLD_MOVE_ESCAPE = 8 // px — a deliberate fast drag engages immediately, no need to wait out the timer

function CanvasBlock({
  block,
  stackIndex,
  images,
  selected,
  onSelect,
  onDeselect,
  onChange,
  onDelete,
  onReorder,
}: {
  block: Block
  stackIndex: number
  images: string[]
  selected: boolean
  onSelect: () => void
  onDeselect: () => void
  onChange: (patch: Partial<Block>) => void
  onDelete: () => void
  onReorder: (action: ReorderAction) => void
}) {
  const [dragging, setDragging] = useState(false)
  const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 })

  // Press-and-HOLD anywhere on the block body to move it — no separate grip
  // icon. Holding past HOLD_DELAY_MS (or moving decisively before that)
  // engages drag; a quick tap/click with no real hold never does, so the
  // browser's normal click/focus behavior proceeds untouched (text stays
  // directly editable). Position commits once on pointerup — same reliable
  // pattern as the resize handle.
  function handleBodyPointerDown(e: React.PointerEvent) {
    const pointerId = e.pointerId
    const target = e.currentTarget
    const start = { x: e.clientX, y: e.clientY }
    let engaged = false
    let last = start

    function engage() {
      if (engaged) return
      engaged = true
      setDragging(true)
      ;(document.activeElement as HTMLElement | null)?.blur?.()
    }

    const holdTimer = window.setTimeout(engage, HOLD_DELAY_MS)

    function onMove(ev: PointerEvent) {
      if (ev.pointerId !== pointerId) return
      last = { x: ev.clientX, y: ev.clientY }
      const dx = last.x - start.x
      const dy = last.y - start.y
      if (!engaged && Math.hypot(dx, dy) > HOLD_MOVE_ESCAPE) engage()
      if (engaged) {
        ev.preventDefault()
        setDragOffset({ x: dx, y: dy })
      }
    }
    function onUp(ev: PointerEvent) {
      if (ev.pointerId !== pointerId) return
      window.clearTimeout(holdTimer)
      window.removeEventListener("pointermove", onMove)
      window.removeEventListener("pointerup", onUp)
      window.removeEventListener("pointercancel", onUp)
      try {
        target.releasePointerCapture(pointerId)
      } catch {
        /* already released */
      }
      if (engaged) {
        const dx = last.x - start.x
        const dy = last.y - start.y
        onChange({ x: clampX(Math.round(block.x + dx), block.width), y: Math.max(0, Math.round(block.y + dy)) })
        setDragging(false)
        setDragOffset({ x: 0, y: 0 })
      }
    }

    try {
      target.setPointerCapture(pointerId)
    } catch {
      /* not supported / already captured elsewhere — window listeners still work */
    }
    window.addEventListener("pointermove", onMove)
    window.addEventListener("pointerup", onUp)
    window.addEventListener("pointercancel", onUp)
  }

  function handleResizePointerDown(e: React.PointerEvent) {
    e.stopPropagation()
    e.preventDefault()
    const start = { x: e.clientX, y: e.clientY, width: block.width, height: block.height }
    function onMove(ev: PointerEvent) {
      const dx = ev.clientX - start.x
      const dy = ev.clientY - start.y
      onChange({
        width: Math.min(Math.max(Math.round(start.width + dx), MIN_BLOCK_WIDTH), CANVAS_WIDTH - block.x),
        height: Math.max(Math.round(start.height + dy), MIN_BLOCK_HEIGHT),
      })
    }
    function onUp() {
      window.removeEventListener("pointermove", onMove)
      window.removeEventListener("pointerup", onUp)
    }
    window.addEventListener("pointermove", onMove)
    window.addEventListener("pointerup", onUp)
  }

  const bg = block.bg ?? (block.type === "card" ? "#ffffff" : "transparent")
  const noPadding = block.type === "image" || block.type === "divider"

  return (
    <Popover open={selected} onOpenChange={(open) => !open && onDeselect()}>
      <PopoverAnchor asChild>
        <div
          className="group absolute"
          style={{
            left: block.x,
            top: block.y,
            width: block.width,
            height: block.height,
            transform: dragging ? `translate(${dragOffset.x}px, ${dragOffset.y}px)` : undefined,
            // Stacking follows array order (what "bring to front" etc. control),
            // not selection — otherwise a reorder wouldn't visibly change
            // anything while the block is still selected. Dragging always wins
            // so the block being moved never dips behind another mid-drag.
            zIndex: dragging ? 9999 : stackIndex + 1,
          }}
        >
          {/* Content — clips its own contents (image/text overflow), but the
              resize handle below is a SIBLING, not a child, so it's never
              clipped even though it visually sits half outside this box. */}
          <div
            onPointerDown={handleBodyPointerDown}
            onClick={(e) => {
              e.stopPropagation()
              onSelect()
            }}
            // touch-none: without it, a touch "hold" starts the browser's own
            // page-scroll gesture before our pointer logic gets a chance to
            // take over. Skipped for cards specifically — their body can
            // contain a scrollable list of children, and touch-action:none
            // on an ancestor can't be re-enabled by a descendant, so it would
            // permanently break scrolling inside a tall card on touch.
            className={`relative h-full w-full cursor-grab overflow-hidden rounded-xl shadow-sm transition-shadow active:cursor-grabbing ${noPadding ? "" : "p-3"} ${block.type === "card" ? "" : "touch-none"} ${selected ? "ring-2 ring-(--royal-blue)" : "ring-1 ring-black/5"} ${block.type === "card" ? "shadow-md" : ""}`}
            style={{ background: bg, color: block.color ?? undefined }}
          >
            {block.type === "card" ? (
              <CardContents block={block} images={images} onChange={onChange} />
            ) : (
              <BlockContent block={block} onChange={onChange} />
            )}
          </div>

          {/* Resize handle — centered on the bottom-right border corner,
              outside the clipped content box above. */}
          <div
            onPointerDown={handleResizePointerDown}
            className="absolute bottom-0 right-0 z-10 grid h-6 w-6 translate-x-1/2 translate-y-1/2 cursor-se-resize touch-none place-items-center rounded-full border-2 border-white bg-brand-900 text-white opacity-0 shadow-sm group-hover:opacity-100"
            title="Drag to resize"
          >
            <MoveDiagonal2 size={12} strokeWidth={2.5} />
          </div>
        </div>
      </PopoverAnchor>
      <PopoverContent
        className="w-auto p-3"
        onOpenAutoFocus={(e) => e.preventDefault()}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="space-y-3">
          {CHOICE_FIELD_TYPES.has(block.type) && (
            <OptionsEditor options={block.options} onChange={(options) => onChange({ options })} />
          )}
          {block.type === "field_link" && <UrlEditor url={block.src} onChange={(src) => onChange({ src })} />}
          <ColorToolbar
            bg={block.bg}
            color={block.color}
            showTextColor={block.type !== "image" && block.type !== "divider"}
            onBg={(bg) => onChange({ bg })}
            onColor={(color) => onChange({ color })}
            onDelete={onDelete}
            onReorder={onReorder}
          />
        </div>
      </PopoverContent>
    </Popover>
  )
}

function CardContents({
  block,
  images,
  onChange,
}: {
  block: Block
  images: string[]
  onChange: (patch: Partial<Block>) => void
}) {
  // Runtime value is never "card" (filtered out of the palette below), but
  // the type here matches newBlock's own parameter type to avoid fighting
  // Array.filter's lack of narrowing on a plain inequality check.
  function addChild(type: Exclude<BlockType, "image">) {
    const child = newBlock(type, 0, 0)
    onChange({ children: [...block.children, child] })
  }
  function addImageChild(src: string) {
    const child = newImageBlock(src, 0, 0)
    onChange({ children: [...block.children, child] })
  }
  function updateChild(id: string, patch: Partial<Block>) {
    onChange({ children: block.children.map((c) => (c.id === id ? { ...c, ...patch } : c)) })
  }
  function removeChild(id: string) {
    onChange({ children: block.children.filter((c) => c.id !== id) })
  }

  return (
    // No pointerdown-stopPropagation here (there used to be one) — that
    // swallowed every press inside a card before it could reach the card's
    // own handleBodyPointerDown on the parent, so cards could never be
    // moved by holding their body. The "+ type" buttons and the image
    // popover trigger below already stopPropagation on their own onClick,
    // which is the narrower thing that actually needed guarding.
    <div className="flex h-full flex-col gap-2 overflow-auto">
      <div className="flex flex-wrap items-center gap-1.5">
        {BLOCK_LIBRARY.filter((b) => b.type !== "card").map((b) => (
          <button
            key={b.type}
            onClick={(e) => {
              e.stopPropagation()
              addChild(b.type)
            }}
            className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-brand-900 hover:bg-slate-50"
          >
            + {b.label}
          </button>
        ))}
        <Popover>
          <PopoverTrigger asChild>
            <button
              onClick={(e) => e.stopPropagation()}
              className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-brand-900 hover:bg-slate-50"
            >
              + image
            </button>
          </PopoverTrigger>
          <PopoverContent className="w-56 p-2" onClick={(e) => e.stopPropagation()}>
            {images.length === 0 ? (
              <p className="text-xs text-slate-400">No images found.</p>
            ) : (
              <ImagePickerGrid images={images} onPick={addImageChild} />
            )}
          </PopoverContent>
        </Popover>
      </div>
      <div className="flex-1 space-y-2 overflow-auto">
        {block.children.length === 0 ? (
          <p className="text-xs text-slate-400">Empty card — add a block above.</p>
        ) : (
          block.children.map((child) => (
            <ChildBlock key={child.id} block={child} onChange={(p) => updateChild(child.id, p)} onDelete={() => removeChild(child.id)} />
          ))
        )}
      </div>
    </div>
  )
}

function ChildBlock({
  block,
  onChange,
  onDelete,
}: {
  block: Block
  onChange: (patch: Partial<Block>) => void
  onDelete: () => void
}) {
  const [open, setOpen] = useState(false)
  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverAnchor asChild>
        <div
          className="relative min-h-[2.5rem] overflow-hidden rounded-lg p-2 ring-1 ring-black/5"
          style={{ background: block.bg ?? "transparent", color: block.color ?? undefined }}
          onClick={(e) => {
            e.stopPropagation()
            setOpen(true)
          }}
        >
          <BlockContent block={block} onChange={onChange} />
        </div>
      </PopoverAnchor>
      <PopoverContent
        className="w-auto p-3"
        onOpenAutoFocus={(e) => e.preventDefault()}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="space-y-3">
          {CHOICE_FIELD_TYPES.has(block.type) && (
            <OptionsEditor options={block.options} onChange={(options) => onChange({ options })} />
          )}
          {block.type === "field_link" && <UrlEditor url={block.src} onChange={(src) => onChange({ src })} />}
          <ColorToolbar
            bg={block.bg}
            color={block.color}
            showTextColor={block.type !== "image" && block.type !== "divider"}
            onBg={(bg) => onChange({ bg })}
            onColor={(color) => onChange({ color })}
            onDelete={onDelete}
          />
        </div>
      </PopoverContent>
    </Popover>
  )
}

function OptionsEditor({ options, onChange }: { options: string[]; onChange: (options: string[]) => void }) {
  return (
    <div>
      <p className="mb-1.5 text-xs font-semibold text-slate-500">Options</p>
      <div className="space-y-1.5">
        {options.map((o, i) => (
          <div key={i} className="flex items-center gap-1.5">
            <input
              value={o}
              onChange={(e) => onChange(options.map((x, j) => (j === i ? e.target.value : x)))}
              className="w-40 flex-1 rounded-lg border border-slate-200 px-2 py-1 text-xs text-slate-900 outline-none focus:border-(--royal-blue)"
            />
            {options.length > 1 && (
              <button
                onClick={() => onChange(options.filter((_, j) => j !== i))}
                className="grid h-6 w-6 shrink-0 place-items-center rounded-md text-rose-600 hover:bg-rose-50"
              >
                ✕
              </button>
            )}
          </div>
        ))}
      </div>
      <button
        onClick={() => onChange([...options, `Option ${options.length + 1}`])}
        className="mt-1.5 text-xs font-semibold text-(--royal-blue) hover:underline"
      >
        + Add option
      </button>
    </div>
  )
}

function UrlEditor({ url, onChange }: { url: string | null; onChange: (v: string) => void }) {
  return (
    <div>
      <p className="mb-1.5 text-xs font-semibold text-slate-500">Link URL</p>
      <input
        value={url ?? ""}
        onChange={(e) => onChange(e.target.value)}
        placeholder="https://…"
        className="w-48 rounded-lg border border-slate-200 px-2 py-1.5 text-xs text-slate-900 outline-none focus:border-(--royal-blue)"
      />
    </div>
  )
}

function ColorToolbar({
  bg,
  color,
  showTextColor = true,
  onBg,
  onColor,
  onDelete,
  onReorder,
}: {
  bg: string | null
  color: string | null
  showTextColor?: boolean
  onBg: (v: string | null) => void
  onColor: (v: string | null) => void
  onDelete: () => void
  /** Omitted for card-nested children — they can't overlap, so layer order is meaningless there. */
  onReorder?: (action: ReorderAction) => void
}) {
  return (
    <div className="space-y-3">
      {onReorder && (
        <div>
          <p className="mb-1.5 text-xs font-semibold text-slate-500">Layer order</p>
          <div className="flex gap-1.5">
            <button
              onClick={() => onReorder("front")}
              title="Bring to front"
              className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"
            >
              <BringToFront size={14} />
            </button>
            <button
              onClick={() => onReorder("forward")}
              title="Bring forward"
              className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"
            >
              <ChevronUp size={14} />
            </button>
            <button
              onClick={() => onReorder("backward")}
              title="Send backward"
              className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"
            >
              <ChevronDown size={14} />
            </button>
            <button
              onClick={() => onReorder("back")}
              title="Send to back"
              className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"
            >
              <SendToBack size={14} />
            </button>
          </div>
        </div>
      )}
      <div>
        <p className="mb-1.5 text-xs font-semibold text-slate-500">Background</p>
        <div className="flex flex-wrap gap-1.5">
          <button
            onClick={() => onBg(null)}
            className={`h-6 w-6 rounded-full border-2 bg-[repeating-conic-gradient(#e2e8f0_0_25%,white_0_50%)] bg-[length:8px_8px] ${bg === null ? "border-(--royal-blue)" : "border-transparent"}`}
            title="None"
          />
          {BG_SWATCHES.map((c) => (
            <button
              key={c}
              onClick={() => onBg(c)}
              style={{ background: c }}
              className={`h-6 w-6 rounded-full border-2 ${bg === c ? "border-(--royal-blue)" : "border-transparent"}`}
            />
          ))}
          <input
            type="color"
            value={bg ?? "#ffffff"}
            onChange={(e) => onBg(e.target.value)}
            className="h-6 w-6 cursor-pointer rounded-full border-2 border-transparent p-0"
          />
        </div>
      </div>
      {showTextColor && (
        <div>
          <p className="mb-1.5 text-xs font-semibold text-slate-500">Text color</p>
          <div className="flex flex-wrap gap-1.5">
            <button
              onClick={() => onColor(null)}
              className={`h-6 w-6 rounded-full border-2 bg-[repeating-conic-gradient(#e2e8f0_0_25%,white_0_50%)] bg-[length:8px_8px] ${color === null ? "border-(--royal-blue)" : "border-transparent"}`}
              title="Default"
            />
            {TEXT_SWATCHES.map((c) => (
              <button
                key={c}
                onClick={() => onColor(c)}
                style={{ background: c }}
                className={`h-6 w-6 rounded-full border-2 ${color === c ? "border-(--royal-blue)" : "border-transparent"}`}
              />
            ))}
          </div>
        </div>
      )}
      <button onClick={onDelete} className="w-full rounded-lg border border-rose-200 py-1.5 text-xs font-semibold text-rose-600 hover:bg-rose-50">
        Delete block
      </button>
    </div>
  )
}
